### PR TITLE
Add a wind speed filter in step1_generate_emission_scenarios.ipynb

### PR DESCRIPTION
**Pull request by maverickjia**
This update introduces a filter in step1_generate_emission_scenarios.ipynb to exclude invalid wind speed values. Specifically, a lower bound (ws_lb) and an upper bound (ws_ub) have been set to define the acceptable range for wind speed values.

### CODE REVIEW

**Review by pdwaggoner — APPROVED** [review]
These changes look good to me. And for what it's worth, here's the new error you get from Ryker's code re: the wind issue: 

```
wind_data(self, ws)
    213 def _check_wind_data(self, ws):
--> 214     if np.any(ws <= 0):
    215         print("[FastGaussianPuff] ERROR: wind speed <= 0 in the input. Exiting.")
    216         exit(-1)

TypeError: '<=' not supported between instances of 'list' and 'int'
```

So, with the combination of your filter and changes, as well as Ryker's fix, this should be good to go from my perspective! Thanks.

**Comment by pdwaggoner** [comment]
@maverickjia the spell check linter flagged these issues (you can also inspect if you look at the checks output):

```
./demo/step1_generate_emission_scenarios.ipynb:155: optinal ==> optional
./demo/step1_generate_emission_scenarios.ipynb:15[6](https://github.com/Hammerling-Research-Group/placement/actions/runs/11827641896/job/32956181962?pr=22#step:4:7): optinal ==> optional
./demo/step1_generate_emission_scenarios.ipynb:237: fo ==> of, for
./demo/step1_generate_emission_scenarios.ipynb:23[7](https://github.com/Hammerling-Research-Group/placement/actions/runs/11827641896/job/32956181962?pr=22#step:4:8): OpeG ==> open
./demo/step1_generate_emission_scenarios.ipynb:237: Ba ==> By, be
Error: Process completed with exit code 65.
```

*Can you verify that these terms are correct, and if not, please correct the spelling?* Thanks!

**Comment by maverickjia** [comment]
I've corrected some of the typos. However, I couldn't locate these 3 errors in step 1 code: 
./demo/step1_generate_emission_scenarios.ipynb:237: fo ==> of, for
./demo/step1_generate_emission_scenarios.ipynb:23[7](https://github.com/Hammerling-Research-Group/placement/actions/runs/11827641896/job/32956181962?pr=22#step:4:8): OpeG ==> open
./demo/step1_generate_emission_scenarios.ipynb:237: Ba ==> By, be

**Comment by pdwaggoner** [comment]
I couldn't either. What I think it is, is in those extremely long num-char strings that are unfortunately unique to jupyter notebooks, it detected some odd combination of characters. As long as you've had a look and the code is correct, that's the most important thing. Thanks! Merged.

**Pull request merged**
